---
- name: Обновить пакеты системы
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: Установить необходимые пакеты для приложения
  apt:
    name:
      - python3
      - python3-pip
      - python3-venv
      - curl
      - wget
      - git
      - gunicorn
    state: present
  become: yes

- name: Создать пользователя приложения
  user:
    name: "{{ app_user }}"
    system: yes
    shell: /bin/bash
    home: "{{ app_dir }}"
    create_home: yes
  become: yes

- name: Создать директорию для приложения
  file:
    path: "{{ app_dir }}"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: '0755'
  become: yes

- name: Создать директорию для логов
  file:
    path: "{{ app_dir }}/logs"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: '0755'
  become: yes

- name: Копировать код приложения
  copy:
    src: "/app/"
    dest: "{{ app_dir }}/app"
    mode: preserve
  become: yes
  become_user: "{{ app_user }}"

- name: Создать виртуальное окружение Python
  pip:
    requirements: "{{ app_dir }}/app/requirements.txt"
    virtualenv: "{{ app_dir }}/venv"
    virtualenv_command: python3 -m venv
  become: yes
  become_user: "{{ app_user }}"

- name: Создать конфигурационный файл приложения
  template:
    src: app_config.j2
    dest: "{{ app_dir }}/app/.env"
    mode: '0600'
  become: yes
  become_user: "{{ app_user }}"

- name: Создать скрипт запуска приложения
  template:
    src: start_app.sh.j2
    dest: "{{ app_dir }}/start_app.sh"
    mode: '0755'
  become: yes
  become_user: "{{ app_user }}"

- name: Создать скрипт запуска приложения
  template:
    src: start_app.sh.j2
    dest: "{{ app_dir }}/start_app.sh"
    mode: '0755'
  become: yes
  become_user: "{{ app_user }}"

- name: Запустить приложение напрямую
  shell: |
    cd {{ app_dir }}/app && nohup {{ app_dir }}/venv/bin/python3 app.py > {{ app_dir }}/logs/app.log 2>&1 &
  args:
    executable: /bin/bash
  become: yes
  become_user: "{{ app_user }}"
  register: app_start

- name: Проверить запуск приложения
  shell: |
    pgrep -f "python3 app.py" || (echo "Приложение не запущено" && exit 1)
  args:
    executable: /bin/bash
  become: yes
  register: app_check
  ignore_errors: yes

- name: Вывести статус приложения
  debug:
    msg: "Приложение запущено: {{ app_check.rc == 0 }}"