---
# Плейбук для деплоя веб-приложения

- name: Деплой веб-приложения
  hosts: app_servers
  become: yes

  vars:
    # Переменные для деплоя приложения
    app_dir: /opt/myapp
    app_user: myapp
    app_group: myapp
    app_repo: ./app  # Локальная директория с приложением
    app_version: main
    app_service_name: myapp
    app_port: 8000
    app_host: 0.0.0.0

    # Конфигурация приложения
    app_config:
      debug: false
      secret_key: "demo-secret-key-$(date +%s)"
      database_url: "sqlite:///app.db"

  roles:
    - app_deploy

  tasks:
    - name: Проверить запуск приложения
      uri:
        url: http://localhost:{{ app_port }}/health
        return_content: yes
      register: app_check
      until: app_check.status == 200
      retries: 5
      delay: 3

    - name: Вывести результат проверки приложения
      debug:
        msg: "Приложение доступно: {{ app_check.status == 200 }}"