---
# Плейбук для деплоя только nginx серверов

- name: Деплой nginx сервера
  hosts: nginx_servers
  become: yes

  vars:
    # Переменные для nginx роли
    nginx_port: 80
    web_root: /var/www/html
    client_max_body_size: 16M

  roles:
    - nginx

  tasks:
    - name: Создать тестовую страницу
      copy:
        dest: "{{ web_root }}/index.html"
        content: |
          <!DOCTYPE html>
          <html lang="ru">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>DevOps Lab - Nginx</title>
              <style>
                  body {
                      font-family: Arial, sans-serif;
                      text-align: center;
                      padding: 50px;
                      background-color: #f0f8ff;
                  }
                  .success { color: #28a745; }
                  .info { color: #17a2b8; }
              </style>
          </head>
          <body>
              <h1 class="success">✅ Nginx успешно развернут!</h1>
              <p class="info">Сервер работает и готов к обслуживанию контента.</p>
              <p><strong>Время развертывания:</strong> {{ ansible_date_time.iso8601 }}</p>
              <p><strong>Хост:</strong> {{ ansible_hostname }}</p>
          </body>
          </html>
        mode: '0644'
      become: yes

    - name: Проверить доступность nginx
      uri:
        url: http://localhost
        return_content: yes
      register: nginx_check
      until: nginx_check.status == 200
      retries: 3
      delay: 2

    - name: Вывести результат проверки
      debug:
        msg: "Nginx доступен: {{ nginx_check.status == 200 }}"