---
# Главный плейбук для деплоя всей инфраструктуры

- name: Деплой nginx сервера
  hosts: nginx_servers
  become: yes
  roles:
    - nginx

- name: Деплой веб-приложения
  hosts: app_servers
  become: yes
  roles:
    - app_deploy